stages:
  - build

deploy:
  stage: build
  only:
    refs:
      - develop-2.0
  script:
        - npm install
        - npm run build
        - mv dist/ $CI_COMMIT_REF_SLUG
        - zip -r $CI_COMMIT_REF_SLUG.zip $CI_COMMIT_REF_SLUG/
        - scp $CI_COMMIT_REF_SLUG.zip calls@vc-dev.enlighted.ru:/var/www/front/ && rm -rf $CI_COMMIT_REF_SLUG.zip
        - ssh calls@vc-dev.enlighted.ru "cd /var/www/front/ && rm -rf $CI_COMMIT_REF_SLUG && unzip $CI_COMMIT_REF_SLUG.zip && rm -rf $CI_COMMIT_REF_SLUG.zip"
        - sh etc/tg.sh "<b>vc-dev.enlighted.ru</b> (frontend) обновлен 🚀🤖"
